# Generated by Django 5.0.3 on 2024-05-03 23:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('google_oauth', '0002_alter_user_google_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folder_name', models.CharField(max_length=100, verbose_name='folder_name')),
                ('google_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='google_oauth.googleuser')),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subs_id', models.CharField(max_length=50, verbose_name='subs_id')),
                ('title', models.CharField(max_length=500, verbose_name='title')),
                ('description', models.CharField(blank=True, max_length=1000, verbose_name='description')),
                ('thumbnails', models.CharField(max_length=200, verbose_name='thumbnails')),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subs_folder.folder')),
            ],
        ),
    ]
